### ISSUE TITLE
Delete le contenu d'un vecteur

### ISSUE THREAD

**Issue by darnuria** [beastboym/astroRust#3]
Plutot que faire erase_vec defini dans function.rs utilisé dans 
```rust
/// Erase a vector's content
pub(crate) fn erase_vec<T>(vec: &mut Vec<T>) {
    for _i in 0..vec.len() {
        vec.pop();
    }
}
```

Je vous recommande juste: `https://doc.rust-lang.org/std/vec/struct.Vec.html#method.clear`

Si vous souhaitez récup la mémoire faire ensuite ou de temps en temps un https://doc.rust-lang.org/std/vec/struct.Vec.html#method.shrink_to_fit

**Comment by beastboym** [comment]
C’est effectivement mieux haha, je ferai de mon mieux pour ne plus essayer de réinventer une roue
